### ISSUE TITLE
Mobile First: proper use of media queries

### ISSUE THREAD

**Issue by FarahZaqout** [FACG5/voyage#23]
You should make sure the app runs on all screen widths and resolutions. 

The way to do that is to start with the mobile design, and then start using queries for larger screens.
on my screen this is how the app looks like
![screenshot from 2018-09-13 01-44-35](https://user-images.githubusercontent.com/25854070/45457221-a0283600-b6f6-11e8-999b-cf0c03c922b0.png)

make sure your media query for the largest screen is set with min width, so if anything is larger than the width specified it will run properly.

**Comment by AsalaKM** [comment]
I solved it :smiley:
