### ISSUE TITLE
Endpoints Should be separated by hyphens.

### ISSUE THREAD

**Issue by FarahZaqout** [FACG5/voyage#35]
Your endpoint are written in ```snake_case```, which is not inherently wrong. However, using ```kebab-case``` is better for search engine optimization.

double click the following words:
some_endpoint
some-endpoint

You will notice the snake_case is considered one word by the browser, while the kebab-case is considered two separate points. This means the indexing and search for endpoints written in kebab-case is much more optimized than searching endpoints in snake_case.

**Comment by donia98** [comment]
Ok, got it ...
